### ISSUE TITLE
Warning: Undefined variable $api_keys_configured in stripe_requirements()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/stripe#31]
> Warning: Undefined variable $api_keys_configured in stripe_requirements() (line 90 of /home/dev/public_html/modules/contrib/stripe/stripe.install).

**Comment by stpaultim** [comment]
I'm going to reopen this issue, because this bug still exists in the latest release. 

This was fixed in Jan 2024, but there has not been a release since then. 

I've solved the problem by now by pulling down the dev version, but others experiencing this problem might be confused if the issue is closed, but the bug persists in the public release.
